### ISSUE TITLE
Discord Embeds not functioning

### ISSUE THREAD

**Issue by Ynd21** [Dan6erbond/share-me#13]
Issue: Using 0.20.0 on Docker, Discord is not embeding the post. 

Debug: http://ynd.one/KXdJ0V

File Column: http://ynd.one/t45qOD

Entire Page (shows thumbnails): http://ynd.one/KR8TPv

Post URL: https://images.yndlabs.com/posts/pehzs1xhhkced6b

How it looks in discord: http://ynd.one/mwJtBC

Was instructed to make an issue to see if someone has seen this before. 

Thanks!

**Comment by Ynd21** [comment]
Sure! 

I'm using Traefik (http://ynd.one/w0y3ap) and routing /api/ to share-me's backend. I don't have /_/ accessible. SSL's are generated via Encryption Everywhere

**Comment by Dan6erbond** [comment]
Hmm, your setup sounds perfectly fine. And since all the other messaging apps and OpenGraph/Twitter validators work, it's hard to really say why Discord cannot generate the previews.

My only guess is that their servers aren't able to reach yours, maybe due to a header being blocked or something. You don't happen to have Fail2Ban or anything 
like that?

I also am not very well versed in the networking side of things, so hopefully someone can chime in that is.

**Comment by Dan6erbond** [comment]
One thing I noticed on mobile browsers is that the trailing slash from /api/ is removed. But that's only the case for direct image links, and I don't think it should affect Discord's scraping. But it might be worth a shot to update.

**Comment by Ynd21** [comment]
So I do use crowdsec and it could be possible its blocking discord. I'll remove the bouncer from that route and see if that helps, as well as closing off the /api/ route on mobile devices

**Comment by Ynd21** [comment]
Was crowdsec :) thanks for that! Closing

**Comment by Dan6erbond** [comment]
Glad to hear you figured it out! Hope that makes Share Me the solution you can use! :)
