### ISSUE TITLE
API Posts Issue

### ISSUE THREAD

**Issue by Ynd21** [Dan6erbond/share-me#30]
Using Postman 

![Postman_rynVMBdiM8](https://github.com/Dan6erbond/share-me/assets/13704380/f6e216a7-84b2-4522-ac20-395f557d8ba5) I receive a 200 Response (below)

API Response:
`{
    "author": "on2imnwqggminrg",
    "collectionId": "tqco9f8weal93h6",
    "collectionName": "posts",
    "created": "2023-05-20 04:23:05.739Z",
    "files": [
        "z1qxne4clk31jlw"
    ],
    "id": "p5othop5v4z4k18",
    "nsfw": false,
    "public": false,
    "tags": null,
    "title": "",
    "updated": "2023-05-20 04:23:05.739Z"
}`

And the file does appear to be uploaded (admin UI) - 

\\Edit: It has to do with the invalid type - when setting it to "image/png", it loads correctly on the frontend. I'm not seeing a way to set this via the api call? 

![chrome_D1uBq0iTaU](https://github.com/Dan6erbond/share-me/assets/13704380/ae121e06-494a-4625-bf26-36204e513167)

The actual post is trying to load a video: 

![chrome_23oHpUIROy](https://github.com/Dan6erbond/share-me/assets/13704380/7362cbb7-9337-46c9-ba2a-811ad0098297)

![chrome_sYyga3a3cB](https://github.com/Dan6erbond/share-me/assets/13704380/aafb3424-5655-48f3-a4ae-feb021946af1)

![chrome_0J74cGu534](https://github.com/Dan6erbond/share-me/assets/13704380/82e4ba93-2d95-4df3-9c3f-561fd76bb696)

**Comment by Dan6erbond** [comment]
Hey! Thanks for the detailed report! Your diagnosis is correct that the frontend doesn't know which MIME type the image has, and then fallbacks to loading a video.

In the future I might change the way it handles unrecognized MIME types to a generic URL so that users can still copy the direct link.

The way MIME types are handled in Share Me generally still needs improvement. I'd like to move away from the frontend sending this information, since it can be easily detected in the backend, which is what #31 does for the `/api/posts` route that I'll migrate the frontend to, soon.

Unfortunately PocketBase doesn't have read-only fields as far as I'm aware. So I'll have to find a different way to make the `type` attribute come from the server side.
