### ISSUE TITLE
A method to disable sign-ups?

### ISSUE THREAD

**Issue by Entheologian** [Dan6erbond/share-me#4]
Is there a method to disable sign-ups?

Thanks,

**Comment by Dan6erbond** [comment]
Yes, as per the [README](https://github.com/Dan6erbond/share-me#authentication) you can disable user sign-ups by going to the users table in PocketBase and going to the authentication settings to disable username/email authentication. This will also hide the sign-up button and page in the frontend.

**Comment by Entheologian** [comment]
My bad, I should have been more clear. What I meant to ask is if there is a way to still require the login, but to disable the sign-up link. This way only users I create can login, without anonymous access.

**Comment by Dan6erbond** [comment]
Ah, yes, it would theoretically be possible if you go to the users collection settings, and remove the "create" rule so that it's admins only. But the frontend doesn't have any checks for that, so the sign-up links and page would still show up. I'll open this issue to add an environment variable for `SIGNUP_ENABLED`.
